// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tests

import (
	"github.com/notefan-golang/config"
	"github.com/notefan-golang/routes"
)

// Injectors from injector.go:

func InitializeApp() (*config.App, error) {
	db, err := config.InitializeDB()
	if err != nil {
		return nil, err
	}
	router := routes.InitializeRouter(db)
	app := config.NewApp(db, router)
	return app, nil
}
