// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package containers

import (
	"database/sql"
	"notefan-golang/controllers"
	"notefan-golang/repositories"
	"notefan-golang/services"
)

// Injectors from injector.go:

func InitializeAuthController(db *sql.DB) *controllers.AuthController {
	userRepository := repositories.NewUserRepository(db)
	authService := services.NewAuthService(userRepository)
	authController := controllers.NewAuthController(authService)
	return authController
}
