CREATE TABLE `user_settings` (
  `id` CHAR(36) PRIMARY KEY,  
  `user_id` CHAR(36) NOT NULL,
  `key` VARCHAR(50) NOT NULL,
  `value` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,

  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;
