CREATE TABLE users (
  id VARCHAR(36) PRIMARY KEY,  
  name VARCHAR(50) NOT NULL,
  email VARCHAR(25) NOT NULL,
  password VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);