CREATE TABLE spaces (
  id VARCHAR(36) PRIMARY KEY,  
  name VARCHAR(50) NOT NULL,
  description VARCHAR(50) NULL,
  domain VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);