CREATE TABLE `page_contents` (
  `id` CHAR(36) PRIMARY KEY,  
  `page_id` CHAR(36) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `order` INT UNSIGNED NOT NULL,
  `body` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,

  CONSTRAINT uc_page_contents UNIQUE (id),
  FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;
